name: Release
on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9

      - name: Build
        run: |
          version=1.0.0.${{github.run_number}}
          sed -i "s/\(<Version>\([0-9]\+\.\)\{3\}\)\([0-9]\+\)/\1${{github.run_number}}/" "DustyPig.CloudPackages/DustyPig.CloudPackages.csproj"
          dotnet pack -c release -o nuget
          dotnet nuget push "nuget/*.nupkg" --skip-duplicate -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json
